export const ActionTypes = {
    SET_MOVIES: "SET_MOVIES",
    SELECTED_MOVIE: "SELECTED_MOVIE",
    REMOVE_SELECTED_MOVIE: "REMOVE_SELECTED_MOVIE",
    deSelectMovie: "deSelectMovie",
    SELECTED_SHOW_INFO: "SELECTED_SHOW_INFO",
    REMOVE_SHOW_INFO: "REMOVE_SHOW_INFO",
    SELECTED_PEOPLE_INFO: "SELECTED_SHOW_INFO",
    REMOVE_PEOPLE_INFO: "REMOVE_PEOPLE_INFO",
}